name: "example config"
out-headers:
  - "name"
  - "can_drink"
  - "date"
  - "age"
transformations:
  - name: "fancify the name"
    out-index: 0
    in-index: 1
    operation: "make_it_fancy"
  - name: "check legal age"
    out-index: 1
    in-index: 2
    operation: "can_drink"
  - name: "copy date"
    out-index: 2
    in-index: 0
    operation: "copy"
  - name: "copy age"
    out-index: 3
    in-index: 2
    operation: "copy"

